# Generated by Django 4.0 on 2022-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(null=True, through='main.Role', to='main.Person'),
        ),
    ]
